version: '3.8'

services:
  db:
    image: postgres:13-alpine
    container_name: ai_postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=rppt
      - POSTGRES_DB=user_management_system
    ports:
      - "5432:5432"
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog
    container_name: ai_mailhog
    ports:
      - "1025:1025" # SMTP port
      - "8025:8025" # Web UI port
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: ai_flask_backend
    environment:
      - DATABASE_URL=postgresql://postgres:rppt@db:5432/user_management_system
      - FRONTEND_URL=http://localhost:8080 
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MAIL_SERVER=mailhog
      - MAIL_PORT=1025
      - MAIL_USE_TLS=False
      - MAIL_USERNAME=
      - MAIL_PASSWORD=
    depends_on:
      - db
    restart: unless-stopped
  
  frontend:
    build: ./frontend
    container_name: ai_vue_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data: