"""Initial architecture

Revision ID: aa1fc94939ee
Revises: 
Create Date: 2026-03-08 10:38:46.539232

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aa1fc94939ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_activity_log_content_id'))
        batch_op.drop_index(batch_op.f('idx_activity_log_event_type'))
        batch_op.drop_index(batch_op.f('idx_activity_log_occurred_at'))
        batch_op.drop_index(batch_op.f('idx_activity_log_user_id'))

    op.drop_table('activity_log')
    with op.batch_alter_table('assessment_attempts', schema=None) as batch_op:
        batch_op.alter_column('score',
               existing_type=sa.NUMERIC(precision=7, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
        batch_op.alter_column('max_score',
               existing_type=sa.NUMERIC(precision=7, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
        batch_op.alter_column('answers',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('assessment_attempts_content_id_student_id_attempt_number_key'), type_='unique')
        batch_op.drop_index(batch_op.f('idx_assessment_attempts_content_id'))
        batch_op.drop_index(batch_op.f('idx_assessment_attempts_student_id'))
        batch_op.drop_constraint(batch_op.f('fk_aa_student_id'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'learning_content', ['learning_content_id'], ['id'])
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['id'])
        batch_op.drop_column('is_submitted')
        batch_op.drop_column('feedback')
        batch_op.drop_column('assessment_id')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('idx_courses_created_by_teacher_id'))
        batch_op.drop_constraint(batch_op.f('fk_courses_teacher_id'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'teachers', ['created_by_teacher_id'], ['id'])

    with op.batch_alter_table('learning_content', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('idx_learning_content_module_id'))
        batch_op.drop_constraint(batch_op.f('learning_content_module_id_content_order_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('fk_learning_content_module_id'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'modules', ['module_id'], ['id'])
        batch_op.drop_column('estimated_duration_minutes')
        batch_op.drop_column('metadata')

    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('idx_modules_course_id'))
        batch_op.drop_constraint(batch_op.f('modules_course_id_module_order_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('fk_modules_course_id'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'courses', ['course_id'], ['id'])

    with op.batch_alter_table('student_content_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_student_content_progress_content_id'))
        batch_op.drop_index(batch_op.f('idx_student_content_progress_student_id'))
        batch_op.drop_constraint(batch_op.f('student_content_progress_student_id_content_id_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('fk_scp_student_id'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_scp_content_id'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['id'])
        batch_op.create_foreign_key(None, 'learning_content', ['content_id'], ['id'])

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('idx_students_user_id'))
        batch_op.drop_constraint(batch_op.f('fk_students_user_id'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('profile_metadata')
        batch_op.drop_column('date_of_birth')
        batch_op.drop_column('grade_level')

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('idx_teachers_user_id'))
        batch_op.drop_constraint(batch_op.f('fk_teachers_user_id'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('bio')

    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.alter_column('granted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('idx_user_roles_role'))
        batch_op.drop_constraint(batch_op.f('fk_user_roles_user_id'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=postgresql.CITEXT(),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=postgresql.CITEXT(),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('idx_users_email'))
        batch_op.drop_index(batch_op.f('idx_users_username'))
        batch_op.drop_column('last_login_at')
        batch_op.drop_column('is_email_verified')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_email_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('last_login_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('idx_users_username'), ['username'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_email'), ['email'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=postgresql.CITEXT(),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=80),
               type_=postgresql.CITEXT(),
               existing_nullable=False)

    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user_roles_user_id'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_user_roles_role'), ['role'], unique=False)
        batch_op.alter_column('granted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_teachers_user_id'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_teachers_user_id'), ['user_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('profile_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_students_user_id'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_students_user_id'), ['user_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('student_content_progress', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_scp_content_id'), 'learning_content', ['content_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_scp_student_id'), 'students', ['student_id'], ['id'], ondelete='CASCADE')
        batch_op.create_unique_constraint(batch_op.f('student_content_progress_student_id_content_id_key'), ['student_id', 'content_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_student_content_progress_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_student_content_progress_content_id'), ['content_id'], unique=False)

    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_modules_course_id'), 'courses', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_unique_constraint(batch_op.f('modules_course_id_module_order_key'), ['course_id', 'module_order'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_modules_course_id'), ['course_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('learning_content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('estimated_duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_learning_content_module_id'), 'modules', ['module_id'], ['id'], ondelete='CASCADE')
        batch_op.create_unique_constraint(batch_op.f('learning_content_module_id_content_order_key'), ['module_id', 'content_order'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_learning_content_module_id'), ['module_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_courses_teacher_id'), 'teachers', ['created_by_teacher_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('idx_courses_created_by_teacher_id'), ['created_by_teacher_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('assessment_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assessment_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('feedback', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_submitted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_aa_student_id'), 'students', ['student_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_assessment_attempts_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_assessment_attempts_content_id'), ['learning_content_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('assessment_attempts_content_id_student_id_attempt_number_key'), ['learning_content_id', 'student_id', 'attempt_number'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('answers',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
        batch_op.alter_column('max_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.NUMERIC(precision=7, scale=2),
               existing_nullable=False)
        batch_op.alter_column('score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.NUMERIC(precision=7, scale=2),
               nullable=True)

    op.create_table('activity_log',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('content_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('duration_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['learning_content.id'], name=op.f('fk_activity_log_content_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_activity_log_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('activity_log_pkey'))
    )
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_activity_log_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_activity_log_occurred_at'), [sa.literal_column('occurred_at DESC')], unique=False)
        batch_op.create_index(batch_op.f('idx_activity_log_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('idx_activity_log_content_id'), ['content_id'], unique=False)

    # ### end Alembic commands ###
